### ISSUE TITLE
Input text background after autocomplete

### ISSUE THREAD

**Issue by nsandor-webDev** [nsandor-webDev/goodrequest-react-task#3]
Set white background #FFF in **StepTwo** component to every text input element after autocomplete.

**Comment by nishit-prasad** [comment]
Hello, is this open for contributions? If so, I would like to work on it and contribute more.

Looking forward. Thanks!

**Comment by nsandor-webDev** [comment]
@nishit-prasad This project is only for job application. If you want, you can solve this issue and learn something new ;) 

Readme is in slovak language and is only for me. Respect it.

**Comment by nishit-prasad** [comment]
Sure. Thank you! I would like to learn more and contribute. Can this be assigned to me?

**Comment by nsandor-webDev** [comment]
@nishit-prasad Go for it !

**Comment by nishit-prasad** [comment]
@nsandor-webDev Thank you!

Question, the input DOMs under StepTwo have respective placeholder texts.

What does autocomplete mean here?

**Comment by nsandor-webDev** [comment]
@nishit-prasad  Autocomplete is when you visit the page, in this case the component loads, and you click on input then your browser offer you remembered data such as name, phone number atc. When you choose some data from history, the inputs background is light blue.

**Comment by nishit-prasad** [comment]
@nsandor-webDev  Thanks for the explanation!

I linked a PR against it that overrides styles of autofills/autocomplete via WebKit.

Thank you for this. I learned something great from it.
